mutation CreateFavoriteOrder($coffeeDrinkId: UUID!, $userId: UUID!, $name: String!) @auth(level: USER) {
  favoriteOrder_insert(data: {coffeeDrinkId: $coffeeDrinkId, userId: $userId, name: $name, createdAt_expr: "request.time"})
}

query ListCoffeeDrinks @auth(level: PUBLIC, insecureReason: "This operation is safe to expose to the public") {
  coffeeDrinks {
    id
    name
    description
    basePrice
    imageUrl
    category
  }
}

query GetCafeById($cafeId: UUID!) @auth(level: PUBLIC, insecureReason: "This operation is safe to expose to the public") {
  cafe(id: $cafeId) {
    id
    name
    address
    latitude
    longitude
    description
    imageUrl
    phoneNumber
    website
  }
}

mutation UpdateUserFavoriteCafe($userId: UUID!, $cafeId: UUID) @auth(level: USER) {
  user_update(key: {id: $userId}, data: {favoriteCafeId: $cafeId})
}